local M = {}

M.list = {
  -- Navigation
  { category = "Navigation", shortcut = "gg / G", description = "Jump to first / last line of file" },
  { category = "Navigation", shortcut = "ctrl-o / ctrl-i", description = "Jump backward / forward in jump list" },
  { category = "Navigation", shortcut = "gf", description = "Go to file under cursor" },
  { category = "Navigation", shortcut = "gd", description = "Go to local definition" },
  { category = "Navigation", shortcut = "%", description = "Jump to matching bracket / paren / brace" },
  { category = "Navigation", shortcut = "H / M / L", description = "Jump to top / middle / bottom of screen" },
  { category = "Navigation", shortcut = "zz / zt / zb", description = "Center / top / bottom current line on screen" },
  { category = "Navigation", shortcut = "'.", description = "Jump to position of last change" },
  { category = "Navigation", shortcut = "ctrl-^", description = "Switch to alternate (previous) buffer" },
  { category = "Navigation", shortcut = "]] / [[", description = "Jump to next / previous section or function" },
  { category = "Navigation", shortcut = "{ / }", description = "Jump to previous / next empty line (paragraph)" },
  { category = "Navigation", shortcut = "( / )", description = "Jump to previous / next sentence" },
  { category = "Navigation", shortcut = "w / b", description = "Move forward / backward one word" },
  { category = "Navigation", shortcut = "W / B", description = "Move forward / backward one WORD (space-separated)" },
  { category = "Navigation", shortcut = "e / ge", description = "Move to end of word / end of previous word" },
  { category = "Navigation", shortcut = "E / gE", description = "Move to end of WORD / end of previous WORD" },
  { category = "Navigation", shortcut = "0 / ^", description = "Move to start of line / first non-blank character" },
  { category = "Navigation", shortcut = "$ / g_", description = "Move to end of line / last non-blank character" },
  { category = "Navigation", shortcut = "f{char}", description = "Find character forward on current line" },
  { category = "Navigation", shortcut = "F{char}", description = "Find character backward on current line" },
  { category = "Navigation", shortcut = "t{char}", description = "Move till (before) character forward on line" },
  { category = "Navigation", shortcut = "T{char}", description = "Move till (after) character backward on line" },
  { category = "Navigation", shortcut = "; / ,", description = "Repeat last f/t/F/T forward / backward" },
  { category = "Navigation", shortcut = "ctrl-f / ctrl-b", description = "Scroll full page down / up" },
  { category = "Navigation", shortcut = "ctrl-d / ctrl-u", description = "Scroll half page down / up" },
  { category = "Navigation", shortcut = "ctrl-e / ctrl-y", description = "Scroll one line down / up (cursor stays)" },
  { category = "Navigation", shortcut = "{n}G", description = "Jump to line n (e.g., 42G goes to line 42)" },
  { category = "Navigation", shortcut = "{n}%", description = "Jump to n% through the file" },
  { category = "Navigation", shortcut = "gj / gk", description = "Move down / up by display line (respects wrapping)" },
  { category = "Navigation", shortcut = "g0 / g$", description = "Start / end of display line (respects wrapping)" },
  { category = "Navigation", shortcut = "g^", description = "First non-blank character of display line" },
  { category = "Navigation", shortcut = "]m / [m", description = "Jump to next / previous method start" },
  { category = "Navigation", shortcut = "]M / [M", description = "Jump to next / previous method end" },
  { category = "Navigation", shortcut = "gD", description = "Go to global definition of symbol under cursor" },
  { category = "Navigation", shortcut = "[{ / ]}", description = "Jump to unmatched { or } brace" },
  { category = "Navigation", shortcut = "[( / ])", description = "Jump to unmatched ( or ) parenthesis" },
  { category = "Navigation", shortcut = "``", description = "Jump to exact position before last jump" },
  { category = "Navigation", shortcut = "`[  / `]", description = "Jump to start / end of last yank or change" },
  { category = "Navigation", shortcut = "`< / `>", description = "Jump to start / end of last visual selection" },
  { category = "Navigation", shortcut = "gi", description = "Re-enter insert mode at last insert position" },
  { category = "Navigation", shortcut = "g; / g,", description = "Go to older / newer change position in change list" },
  { category = "Navigation", shortcut = ":jumps", description = "Show the full jump list" },
  { category = "Navigation", shortcut = ":changes", description = "Show the change list" },
  { category = "Navigation", shortcut = "zj / zk", description = "Jump to start of next / end of previous fold" },
  { category = "Navigation", shortcut = "[z / ]z", description = "Jump to start / end of the current open fold" },
  { category = "Navigation", shortcut = "ctrl-]", description = "Jump to tag under cursor (ctags)" },
  { category = "Navigation", shortcut = "ctrl-t", description = "Pop the tag stack (go back from tag jump)" },
  { category = "Navigation", shortcut = "gF", description = "Go to file under cursor at the line number" },
  { category = "Navigation", shortcut = "ctrl-w gf", description = "Open file under cursor in a new tab" },
  { category = "Navigation", shortcut = ":find {file}", description = "Find file in 'path' and open it" },
  { category = "Navigation", shortcut = ":pwd", description = "Print the current working directory" },
  { category = "Navigation", shortcut = ":cd {dir}", description = "Change working directory globally" },
  { category = "Navigation", shortcut = ":lcd {dir}", description = "Change working directory for current window only" },
  { category = "Navigation", shortcut = ":tcd {dir}", description = "Change working directory for current tab only" },
  { category = "Navigation", shortcut = "- (minus)", description = "Open netrw in the directory of the current file" },
  { category = "Navigation", shortcut = "gx", description = "Open URL or file under cursor in the OS default app" },
  { category = "Navigation", shortcut = "2fa", description = "Find the 2nd occurrence of 'a' forward on line" },
  { category = "Navigation", shortcut = "5j", description = "Move 5 lines down (any motion accepts a count)" },
  { category = "Navigation", shortcut = ":b {name}", description = "Jump to buffer by partial name match" },
  { category = "Navigation", shortcut = ":bnext / :bprev", description = "Switch to next / previous buffer" },
  { category = "Navigation", shortcut = "[/ / ]/", description = "Jump to previous / next C-style block comment" },
  { category = "Navigation", shortcut = ":tags", description = "Show the tag stack" },
  { category = "Navigation", shortcut = ":tjump {tag}", description = "Jump to tag if unique, else show selection" },
  { category = "Navigation", shortcut = ":tselect {tag}", description = "Show a list of matching tags to choose from" },
  { category = "Navigation", shortcut = "ctrl-w F", description = "Open file:line under cursor in a new split" },
  { category = "Navigation", shortcut = ":sfind {file}", description = "Split and find file in 'path'" },
  { category = "Navigation", shortcut = ":tabfind {file}", description = "Find file and open it in a new tab" },
  { category = "Navigation", shortcut = ":edit .", description = "Open netrw directory browser for current dir" },
  { category = "Navigation", shortcut = "vG", description = "Visually select from cursor to end of file" },
  { category = "Navigation", shortcut = "vgg", description = "Visually select from cursor to start of file" },
  { category = "Navigation", shortcut = "v%", description = "Visually select to the matching bracket" },
  { category = "Navigation", shortcut = "{n}ctrl-w _", description = "Set current window height to n lines" },
  { category = "Navigation", shortcut = ":tjump /pattern", description = "Select a tag matching pattern from a list" },
  { category = "Navigation", shortcut = "g ctrl-g", description = "Show cursor position: line, col, word, byte counts" },
  { category = "Navigation", shortcut = "ctrl-g", description = "Show filename and cursor position info" },
  { category = "Navigation", shortcut = "1ctrl-g", description = "Show full file path and position info" },
  { category = "Navigation", shortcut = ":Explore / :Ex", description = "Open netrw file explorer in current window" },
  { category = "Navigation", shortcut = ":Sexplore / :Sex", description = "Open netrw in a horizontal split" },
  { category = "Navigation", shortcut = ":Vexplore / :Vex", description = "Open netrw in a vertical split" },
  { category = "Navigation", shortcut = ":Texplore / :Tex", description = "Open netrw in a new tab" },
  -- Text Objects
  { category = "Text Objects", shortcut = "iw", description = "Inner word — select word without surrounding spaces" },
  { category = "Text Objects", shortcut = "aw", description = "A word — select word with surrounding spaces" },
  { category = "Text Objects", shortcut = "iW", description = "Inner WORD — non-blank sequence without spaces" },
  { category = "Text Objects", shortcut = "aW", description = "A WORD — WORD including surrounding whitespace" },
  { category = "Text Objects", shortcut = "is", description = "Inner sentence — select sentence without spaces" },
  { category = "Text Objects", shortcut = "as", description = "A sentence — sentence with following whitespace" },
  { category = "Text Objects", shortcut = "ip", description = "Inner paragraph — select paragraph content" },
  { category = "Text Objects", shortcut = "ap", description = "A paragraph — paragraph with following blank line" },
  { category = "Text Objects", shortcut = "i( / ib", description = "Inner parentheses — content inside ()" },
  { category = "Text Objects", shortcut = "a( / ab", description = "A parenthesized block — content including ()" },
  { category = "Text Objects", shortcut = "i{ / iB", description = "Inner curly brace — content inside {}" },
  { category = "Text Objects", shortcut = "a{ / aB", description = "A curly brace block — content including {}" },
  { category = "Text Objects", shortcut = "i[", description = "Inner square bracket — content inside []" },
  { category = "Text Objects", shortcut = "a[", description = "A square bracket block — content including []" },
  { category = "Text Objects", shortcut = "i<", description = "Inner angle bracket — content inside <>" },
  { category = "Text Objects", shortcut = "a<", description = "An angle bracket block — content including <>" },
  { category = "Text Objects", shortcut = "i\"", description = "Inner double-quoted string — content inside \"\"" },
  { category = "Text Objects", shortcut = "a\"", description = "A double-quoted string — content including quotes" },
  { category = "Text Objects", shortcut = "i'", description = "Inner single-quoted string — content inside ''" },
  { category = "Text Objects", shortcut = "a'", description = "A single-quoted string — content including quotes" },
  { category = "Text Objects", shortcut = "i`", description = "Inner backtick string — content inside ``" },
  { category = "Text Objects", shortcut = "a`", description = "A backtick string — content including backticks" },
  { category = "Text Objects", shortcut = "it", description = "Inner tag — content inside HTML/XML tag" },
  { category = "Text Objects", shortcut = "at", description = "A tag block — content including opening/closing tags" },
  { category = "Text Objects", shortcut = "ci(", description = "Change inside parentheses — a common idiom" },
  { category = "Text Objects", shortcut = "di\"", description = "Delete inside double quotes" },
  { category = "Text Objects", shortcut = "ya{", description = "Yank a curly brace block including the braces" },
  { category = "Text Objects", shortcut = "vi[", description = "Visually select inside square brackets" },
  { category = "Text Objects", shortcut = "ca'", description = "Change a single-quoted string including the quotes" },
  { category = "Text Objects", shortcut = "dap", description = "Delete a paragraph including trailing blank line" },
  { category = "Text Objects", shortcut = "yip", description = "Yank inner paragraph" },
  { category = "Text Objects", shortcut = "cis", description = "Change inner sentence" },
  { category = "Text Objects", shortcut = "vis", description = "Visually select inner sentence" },
  { category = "Text Objects", shortcut = "daW", description = "Delete a WORD including surrounding whitespace" },
  { category = "Text Objects", shortcut = "2ciw", description = "Change the next two words (count + text object)" },
  { category = "Text Objects", shortcut = "ct(", description = "Change from cursor till open paren (exclusive)" },
  { category = "Text Objects", shortcut = "dt;", description = "Delete from cursor till semicolon" },
  { category = "Text Objects", shortcut = "yt,", description = "Yank from cursor till comma" },
  { category = "Text Objects", shortcut = "vit then o", description = "Select inside tag, then o moves to other end" },
  { category = "Text Objects", shortcut = "dat", description = "Delete a tag including its attributes and content" },
  { category = "Text Objects", shortcut = "vi\" then ~", description = "Toggle case of content inside double quotes" },
  { category = "Text Objects", shortcut = "dib = di(", description = "ib and b are synonyms for ) in text objects" },
  { category = "Text Objects", shortcut = "daB = da{", description = "aB and B are synonyms for } in text objects" },
  { category = "Text Objects", shortcut = ":help text-objects", description = "Full text object reference in Vim help" },
  { category = "Text Objects", shortcut = "vaw then p", description = "Replace a word with clipboard content" },
  { category = "Text Objects", shortcut = "3daw", description = "Delete 3 words with surrounding spaces" },
  { category = "Text Objects", shortcut = "Text objects + .", description = "Text object operations are repeatable with dot" },
  { category = "Text Objects", shortcut = "cit then type", description = "Change inner tag content and type replacement" },
  { category = "Text Objects", shortcut = "gUiw", description = "Uppercase the inner word under cursor" },
  { category = "Text Objects", shortcut = "guap", description = "Lowercase an entire paragraph" },
  { category = "Text Objects", shortcut = "=i{", description = "Auto-indent the content inside curly braces" },
  -- Search & Replace
  { category = "Search", shortcut = "*  / #", description = "Search forward / backward for word under cursor" },
  { category = "Search", shortcut = "gn", description = "Select next search match (visual)" },
  { category = "Search", shortcut = "cgn", description = "Change next search match — combine with . to repeat" },
  { category = "Search", shortcut = ":%s/foo/bar/gc", description = "Replace foo with bar, confirm each match" },
  { category = "Search", shortcut = ":g/pattern/d", description = "Delete all lines matching pattern" },
  { category = "Search", shortcut = ":v/pattern/d", description = "Delete all lines NOT matching pattern" },
  { category = "Search", shortcut = "/ {pattern}", description = "Search forward for pattern" },
  { category = "Search", shortcut = "? {pattern}", description = "Search backward for pattern" },
  { category = "Search", shortcut = "n / N", description = "Next / previous match (same / opposite direction)" },
  { category = "Search", shortcut = "g* / g#", description = "Search partial word forward / backward (no boundary)" },
  { category = "Search", shortcut = ":noh / :nohlsearch", description = "Clear search highlighting" },
  { category = "Search", shortcut = "\\c in pattern", description = "Force case-insensitive for this search only" },
  { category = "Search", shortcut = "\\C in pattern", description = "Force case-sensitive for this search only" },
  { category = "Search", shortcut = ":%s/foo/bar/g", description = "Replace all occurrences in file" },
  { category = "Search", shortcut = ":%s/foo/bar/gi", description = "Replace all occurrences, case-insensitively" },
  { category = "Search", shortcut = ":s/foo/bar/", description = "Replace first match on current line only" },
  { category = "Search", shortcut = ":s/foo/bar/g", description = "Replace all matches on current line" },
  { category = "Search", shortcut = ":10,20s/foo/bar/g", description = "Replace in lines 10 through 20" },
  { category = "Search", shortcut = ":%s/\\bword\\b/new/g", description = "Replace whole words only (not substrings)" },
  { category = "Search", shortcut = ":%s/^/prefix/", description = "Add a prefix to the start of every line" },
  { category = "Search", shortcut = ":%s/$/ suffix/", description = "Append a suffix to the end of every line" },
  { category = "Search", shortcut = ":g/pattern/p", description = "Print all lines matching pattern" },
  { category = "Search", shortcut = ":g/pattern/y A", description = "Yank all matching lines into register A" },
  { category = "Search", shortcut = ":g/pattern/norm @a", description = "Run macro a on every line matching pattern" },
  { category = "Search", shortcut = ":g/pattern/s/old/new/g", description = "Replace only on lines matching pattern" },
  { category = "Search", shortcut = "gN", description = "Select previous search match (visual)" },
  { category = "Search", shortcut = "dgn", description = "Delete the next search match" },
  { category = "Search", shortcut = "ygn", description = "Yank the next search match" },
  { category = "Search", shortcut = "&", description = "Repeat last :s substitution command" },
  { category = "Search", shortcut = "\\v in pattern", description = "Very magic mode — most chars are special (regex-like)" },
  { category = "Search", shortcut = "\\V in pattern", description = "Very nomagic — only \\ is special (literal search)" },
  { category = "Search", shortcut = "\\zs / \\ze", description = "Mark start / end of match within pattern" },
  { category = "Search", shortcut = "\\%V", description = "Match only inside the last visual selection" },
  { category = "Search", shortcut = ":vimgrep /pat/ **", description = "Grep recursively through all files into quickfix" },
  { category = "Search", shortcut = ":vimgrep /pat/ *.lua", description = "Grep only lua files into quickfix" },
  { category = "Search", shortcut = "q/", description = "Open search history in an editable window" },
  { category = "Search", shortcut = "ctrl-r / (cmdline)", description = "Paste last search pattern into command line" },
  { category = "Search", shortcut = "* then cgn . . .", description = "Efficiently change all occurrences of a word" },
  { category = "Search", shortcut = ":%s/\\v(foo)(bar)/\\2\\1/", description = "Swap foo and bar using capture groups" },
  { category = "Search", shortcut = "/\\<word\\>", description = "Search for exact whole word" },
  { category = "Search", shortcut = "/\\v(foo|bar)", description = "Search for foo or bar using very magic mode" },
  { category = "Search", shortcut = ":%s/\\n//", description = "Join all lines by removing newlines" },
  { category = "Search", shortcut = ":%s/\\r//g", description = "Remove Windows carriage returns (CR) from file" },
  -- Visual Mode
  { category = "Visual", shortcut = "vip / vap", description = "Select inner / outer paragraph" },
  { category = "Visual", shortcut = "o (visual)", description = "Move to other end of selection" },
  { category = "Visual", shortcut = "ctrl-v then I", description = "Insert text at start of each selected line" },
  { category = "Visual", shortcut = "ctrl-v then A", description = "Append text at end of each selected line" },
  { category = "Visual", shortcut = "gv", description = "Reselect last visual selection" },
  { category = "Visual", shortcut = "v", description = "Enter character-wise visual mode" },
  { category = "Visual", shortcut = "V", description = "Enter line-wise visual mode" },
  { category = "Visual", shortcut = "ctrl-v", description = "Enter block (column) visual mode" },
  { category = "Visual", shortcut = "O (block visual)", description = "Move to other corner of block selection" },
  { category = "Visual", shortcut = "viw", description = "Visually select inner word" },
  { category = "Visual", shortcut = "vaw", description = "Visually select word with surrounding spaces" },
  { category = "Visual", shortcut = "vi(", description = "Visually select inside parentheses" },
  { category = "Visual", shortcut = "va{", description = "Visually select inside and including curly braces" },
  { category = "Visual", shortcut = "vit", description = "Visually select inside an HTML/XML tag" },
  { category = "Visual", shortcut = "ctrl-v then c", description = "Change content of each column in block" },
  { category = "Visual", shortcut = "ctrl-v then r{char}", description = "Replace each cell in block with character" },
  { category = "Visual", shortcut = "ctrl-v then d", description = "Delete the selected block" },
  { category = "Visual", shortcut = "V then J", description = "Join all visually selected lines into one" },
  { category = "Visual", shortcut = "V then >", description = "Indent selected lines" },
  { category = "Visual", shortcut = "V then <", description = "Unindent selected lines" },
  { category = "Visual", shortcut = "V then =", description = "Auto-indent selected lines" },
  { category = "Visual", shortcut = "V then gq", description = "Reformat selected lines to textwidth" },
  { category = "Visual", shortcut = "V then :sort", description = "Sort visually selected lines" },
  { category = "Visual", shortcut = "v then ~", description = "Toggle case of visual selection" },
  { category = "Visual", shortcut = "v then gu", description = "Lowercase the visual selection" },
  { category = "Visual", shortcut = "v then gU", description = "Uppercase the visual selection" },
  { category = "Visual", shortcut = "v then p", description = "Paste over the visual selection" },
  { category = "Visual", shortcut = "v then ! {cmd}", description = "Filter selection through external shell command" },
  { category = "Visual", shortcut = "v then :", description = "Open command line with '<,'> range pre-filled" },
  { category = "Visual", shortcut = "V10j", description = "Select current + 10 more lines in visual line mode" },
  { category = "Visual", shortcut = "ctrl-v then $A", description = "Append to each line of different lengths in block" },
  { category = "Visual", shortcut = "ctrl-v on irregular lines", description = "$ in block selects to end of each line" },
  { category = "Visual", shortcut = "v% then action", description = "Select to matching bracket, then operate" },
  { category = "Visual", shortcut = "Visual then \"ay", description = "Yank visual selection into named register a" },
  { category = "Visual", shortcut = "Visual then \"+y", description = "Yank visual selection to system clipboard" },
  { category = "Visual", shortcut = "V then :g/pat/d", description = "Delete matching lines within visual selection" },
  { category = "Visual", shortcut = "Repeat insert in block", description = "ctrl-v, I, type, Esc applies to all selected lines" },
  { category = "Visual", shortcut = "ctrl-v block numbers", description = "Use block visual to visually insert line numbers" },
  { category = "Visual", shortcut = "v then y then P", description = "Duplicate visual selection inline" },
  { category = "Visual", shortcut = "vib", description = "Visually select inside the nearest bracket block" },
  -- Tabs
  -- Command Line

  -- Marks & Jumps
  { category = "Marks", shortcut = "ma / 'a / `a", description = "Set mark a / jump to line / jump to exact position" },
  { category = "Marks", shortcut = ":marks", description = "List all marks" },
  { category = "Marks", shortcut = "''", description = "Jump back to position before last jump" },
  { category = "Marks", shortcut = "mA - mZ", description = "Set global mark (uppercase) — works across files" },
  { category = "Marks", shortcut = "'A - 'Z", description = "Jump to global mark — opens the file if needed" },
  { category = "Marks", shortcut = "Marks a-z are buffer-local", description = "Each file has its own independent mark namespace" },
  { category = "Marks", shortcut = "Marks A-Z are global", description = "Global marks persist across files and sessions" },
  { category = "Marks", shortcut = "'0", description = "Jump to position when Vim was last exited" },
  { category = "Marks", shortcut = "'1 - '9", description = "Previous exit positions (history of last exits)" },
  { category = "Marks", shortcut = "d'a", description = "Delete from cursor to the line of mark a" },
  { category = "Marks", shortcut = "y`a", description = "Yank from cursor to exact position of mark a" },
  { category = "Marks", shortcut = "c'a", description = "Change from cursor to the line of mark a" },
  { category = "Marks", shortcut = "v`a then action", description = "Visually select to mark, then operate on it" },
  { category = "Marks", shortcut = ":delmarks a", description = "Delete a specific mark" },
  { category = "Marks", shortcut = ":delmarks a-z", description = "Delete marks a through z" },
  { category = "Marks", shortcut = ":delmarks!", description = "Delete all lowercase marks" },
  { category = "Marks", shortcut = "'< / '>", description = "Jump to start / end of last visual selection" },
  { category = "Marks", shortcut = "'[ / ']", description = "Jump to start / end of last yank or change" },
  { category = "Marks", shortcut = "Marks persist in shada", description = "Marks are saved to shada file between sessions" },
  { category = "Marks", shortcut = "Use marks for navigation", description = "Set mark at top of function, jump back easily" },
  { category = "Marks", shortcut = "m, before big changes", description = "Set a mark before a large edit to jump back" },
  { category = "Marks", shortcut = ":g/pattern/ mark a", description = "Set mark a on every line matching pattern" },
  { category = "Marks", shortcut = "Combine with :global", description = "Use marks as targets in :global commands" },
  { category = "Marks", shortcut = "'.", description = "Jump to line of last change (shorthand for mark .)" },
  { category = "Marks", shortcut = "`.", description = "Jump to exact position of last change" },
  { category = "Marks", shortcut = "`. then i", description = "Jump to last change and continue editing there" },
  { category = "Marks", shortcut = "Signs show marks", description = "Marks may appear as signs in the signcolumn" },
  { category = "Marks", shortcut = "mM on center screen", description = "Use M mark for 'middle' — jump back with 'M" },
  { category = "Marks", shortcut = "d`b", description = "Delete from cursor to exact position of mark b" },
  -- Spell Checking
  -- QuickFix & Location List
  -- Options & Settings
  -- Misc
  -- Motions (additional)
  { category = "Motions", shortcut = "d / y / c + motion", description = "Operators combine with any motion" },
  { category = "Motions", shortcut = "d3w", description = "Delete 3 words forward" },
  { category = "Motions", shortcut = "c$", description = "Change from cursor to end of line" },
  { category = "Motions", shortcut = "y0", description = "Yank from cursor to start of line" },
  { category = "Motions", shortcut = "d^", description = "Delete from first non-blank character to cursor" },
  { category = "Motions", shortcut = ">j", description = "Indent current and next line" },
  { category = "Motions", shortcut = "<G", description = "Unindent from current line to end of file" },
  { category = "Motions", shortcut = "3}", description = "Move 3 paragraphs forward" },
  { category = "Motions", shortcut = "d/pattern", description = "Delete from cursor to next occurrence of pattern" },
  { category = "Motions", shortcut = "y/bar", description = "Yank from cursor to next occurrence of 'bar'" },
  { category = "Motions", shortcut = "c?prev", description = "Change backward from cursor to 'prev'" },
  { category = "Motions", shortcut = "Marks as motions", description = "d'a deletes from cursor to line of mark a" },
  { category = "Motions", shortcut = "v`a", description = "Visually select from cursor to exact mark position" },
  { category = "Motions", shortcut = "_ motion", description = "Current line (linewise) — useful in operators" },
  { category = "Motions", shortcut = "Linewise motions", description = "j/k/G etc operate on whole lines with operators" },
  { category = "Motions", shortcut = "Exclusive motions", description = "f/t/w don't include the final character" },
  { category = "Motions", shortcut = "Inclusive motions", description = "e/]/% do include the final character" },
  { category = "Motions", shortcut = "2f(", description = "Find the 2nd open paren on the line" },
  { category = "Motions", shortcut = "dt)", description = "Delete from cursor up to (not including) next )" },
  { category = "Motions", shortcut = "cf,", description = "Change from cursor through and including next comma" },
  { category = "Motions", shortcut = "yf.", description = "Yank from cursor through next period" },
  { category = "Motions", shortcut = "Operator + [count] + motion", description = "3dw = delete 3 words, d3w same thing" },
  -- Abbreviations
  -- Git Integration
}

return M
